### ISSUE TITLE
kairos-smi bug (alpha ver.)

### ISSUE THREAD

**Issue by 2KangHo** [kairos03/kairos-smi#19]
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ksmi/__main__.py", line 4, in <module>                                                       
    kairos_smi.main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ksmi/kairos_smi.py", line 146, in main
    ui.display(screen, HOSTS, result)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ksmi/ui.py", line44, in display
    active_gpus = len(set(app_info[0] for app_info in app_stat))
TypeError: 'NoneType' object is not iterable
```

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Version 0.2.2a1

**Comment by kairos03** [comment]
related #16
